name: deploy-k8s-services
description: Check out the lastest repo and check Terraform code correctness

inputs:
  AWS_REGION:
    description: The AWS region where the S3 bucket is located
    required: true
  ENVIRONMENT:
    description: The Github Environment
    required: true
# inputs:
#   ENVIRONMENT:
#     description: The environment to check against
#     required: true
  # AWS_REGION:
  #   description: The AWS region where the S3 bucket is located
  #   required: true
  # AWS_IAM_ROLE_ARN:
  #   description: The ARN of the IAM Role with the proper permissions to assume
  #   required: true

runs:
  using: "composite"

  steps:
  - name: Checkout
    uses: actions/checkout@v4
  # - name: Configure AWS credentials
  #   uses: aws-actions/configure-aws-credentials@v4
  #   with:
  #     role-to-assume: ${{ inputs.AWS_IAM_ROLE_ARN }}
  #     aws-region: ${{ inputs.AWS_REGION }}
  - name: Do it!
    run: |
      echo deploy-k8s-services job ${{ inputs.ENVIRONMENT }} is here at ${{ inputs.AWS_REGION }}!
    shell: bash
