name: Deploy from feature branch

on:
  push:
    branches:
      - 'feature/*'
  # workflow_dispatch:

jobs:
  terraform-check-on-dev:
    name: Terraform check on dev
    runs-on: ubuntu-latest
    environment: dev
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: terraform-lint
      uses: ./.github/actions/terraform-check-fmt-lint
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
    - name: terraform-plan
      uses: ./.github/actions/terraform-plan
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
      #TODO Save Terraform plan file and metadata

  terraform-approve-on-dev:
    name: Terraform approve on dev
    runs-on: ubuntu-latest
    needs: [terraform-check-on-dev]
    environment: manual-approve-dev
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Approved
      run: echo "Approved"

  terraform-deploy-on-dev:
    name: Terraform deploy on dev
    runs-on: ubuntu-latest
    needs: [terraform-approve-on-dev]
    environment: dev
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    #TODO Restore Terraform plan file and metadata
    - name: terraform-apply
      uses: ./.github/actions/terraform-apply
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role

  helm-check-on-dev:
    name: Helm check on dev
    runs-on: ubuntu-latest
    needs: [terraform-deploy-on-dev]
    environment: dev
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: validate-helm-charts
      uses: ./.github/actions/validate-helm-charts
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
    - name: dryrun-k8s-services
      uses: ./.github/actions/dryrun-k8s-services
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role

  helm-deploy-on-dev:
    name: Helm deploy on dev
    runs-on: ubuntu-latest
    needs: [helm-check-on-dev]
    environment: dev
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: deploy-k8s-services
      uses: ./.github/actions/deploy-k8s-services
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role

  commit-deployment-on-dev:
    name: Commit deployment on dev
    runs-on: ubuntu-latest
    needs: [terraform-deploy-on-dev, helm-deploy-on-dev]
    environment: dev
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: commit-deployment
      uses: ./.github/actions/commit-deployment
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role

  check-on-test:
    name: Check on test
    runs-on: ubuntu-latest
    environment: test
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: terraform-plan
      uses: ./.github/actions/terraform-plan
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
    - name: validate-helm-charts
      uses: ./.github/actions/validate-helm-charts
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
    - name: dryrun-k8s-services
      uses: ./.github/actions/dryrun-k8s-services
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role

  check-on-prod:
    name: Check on prod
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: terraform-plan
      uses: ./.github/actions/terraform-plan
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
    - name: validate-helm-charts
      uses: ./.github/actions/validate-helm-charts
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
    - name: dryrun-k8s-services
      uses: ./.github/actions/dryrun-k8s-services
      with:
        AWS_REGION: ${{ vars.AWS_REGION }}
        ENVIRONMENT: ${{ vars.STAGE }}
      # with:
      #   AWS_REGION: ${{ vars.AWS_REGION }}
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role

