name: Deploy from feature branch

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  terraform-check-on-dev:
    name: Terraform check on Development
    runs-on: ubuntu-latest
    environment: Development
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: terraform-lint
      uses: ./.github/actions/terraform-check-fmt-lint
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: dev
    - name: terraform-plan
      uses: ./.github/actions/terraform-plan
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: dev
      #TODO Save Terraform plan file and metadata

  terraform-deploy-on-dev:
    name: Terraform deploy on Development
    runs-on: ubuntu-latest
    needs: [terraform-check-on-dev]
    environment: Development
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    #TODO Restore Terraform plan file and metadata
    - name: terraform-apply
      uses: ./.github/actions/terraform-apply
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: dev

  helm-check-on-dev:
    name: Helm check on Development
    runs-on: ubuntu-latest
    environment: Development
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: validate-helm-charts
      uses: ./.github/actions/validate-helm-charts
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: dev
    - name: dryrun-k8s-services
      uses: ./.github/actions/dryrun-k8s-services
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: dev

  helm-deploy-on-dev:
    name: Helm deploy on Development
    runs-on: ubuntu-latest
    needs: [helm-check-on-dev]
    environment: Development
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: deploy-k8s-services
      uses: ./.github/actions/deploy-k8s-services
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: dev

  commit-deployment-on-dev:
    name: Commit deployment on Development
    runs-on: ubuntu-latest
    needs: [terraform-deploy-on-dev, helm-deploy-on-dev]
    environment: Development
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: commit-deployment
      uses: ./.github/actions/commit-deployment
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: dev

  check-on-test:
    name: Check on Test
    runs-on: ubuntu-latest
    environment: Test
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: terraform-plan
      uses: ./.github/actions/terraform-plan
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: test
    - name: validate-helm-charts
      uses: ./.github/actions/validate-helm-charts
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: test
    - name: dryrun-k8s-services
      uses: ./.github/actions/dryrun-k8s-services
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: test

  check-on-prod:
    name: Check on Production
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      id-token: write
      contents: read
    timeout-minutes: 45
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: terraform-plan
      uses: ./.github/actions/terraform-plan
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: prod
    - name: validate-helm-charts
      uses: ./.github/actions/validate-helm-charts
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: prod
    - name: dryrun-k8s-services
      uses: ./.github/actions/dryrun-k8s-services
      with:
        # AWS_REGION: us-east-1
        # AWS_IAM_ROLE_ARN: arn:aws:iam::973669856136:role/ace-marketing-dev-github-actions-oidc-role
        ENVIRONMENT: prod

