name: commit-deployment
description: Commit a git tag for the deployment

inputs:
  ENVIRONMENT:
    description: The Github Environment
    required: true

runs:
  using: "composite"

  steps:
  - name: Checkout
    uses: actions/checkout@v4
  - name: Do it!
    run: |
      echo commit-deployment job on ${{ inputs.ENVIRONMENT }} is here!
    shell: bash
